### PR TITLE
replace linter with xo

### LINKED ISSUE #21: tests succeed but build is broken
looks like some yarn issue is holding it up

### PR DESCRIPTION
**Pull request by osdiab**
no need to accept this and the changes i'll be adding, I'm working off of my own master branch but i figured the changes I'm applying to this library, could be useful to you - so i'll open these as PRs and if you like them feel free to use them :)

incidentally closes #21 

- tslint is already deprecated
- xo is a wrapper around eslint that provides a bunch of sensible defaults so as to minimize configuration
- replaces tslint with xo
- runs autofix on existing code to format it to style
- ~~as well as some hints for vscode users like myself on how to integrate it into workflow~~

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -1,37 +1,46 @@
...
-                + ` but instead got: ${jsToString(error.value)}.`
-        );
-    }))
+  return pipe(
+    maybeErrorContext,
+    map((errorContext) => {
+      const expectedType = errorContext.type.name;
+      return (
+        // https://github.com/elm-lang/core/blob/18c9e84e975ed22649888bfad15d1efdb0128ab2/src/Native/Json.js#L199
+        // tslint:disable-next-line:prefer-template
```
Comment (osdiab) [inline src/index.ts]:
```suggestion
```

**Comment by lo1tuma** [comment]
Doesn’t xo require an additional shared config to be installed for the [use of typescript](https://github.com/xojs/xo#typescript-and-flow) (i.e. `eslint-config-xo-typescript`)?

File: .gitignore [hunk 2]
```diff
@@ -1,2 +1,13 @@
 /node_modules/
 /target/
+
+# VSCode
```
Comment (lo1tuma) [inline .gitignore]: IMHO IDE-specific files should belong in your personal .gitignore file, not in project ignore files, see also http://stratus3d.com/blog/2018/06/03/stop-excluding-editor-temp-files-in-gitignore/

Comment (osdiab) [reply .gitignore]: sure, will remove. i usually just leave them since i find it helpful to get tips from a maintainer on what works well for a given ide, but doesn't have to be in code or anything

**Comment by osdiab** [comment]
@lo1tuma  it comes with it pre-installed https://github.com/xojs/xo/blob/master/package.json#L62

**Comment by osdiab** [comment]
removed the editor files

**Review by gillchristian — APPROVED** [review]
Seems good to me 👌

**Review by lo1tuma — APPROVED** [review]

**Comment by gillchristian** [comment]
@osdiab once conflicts are solved this can be merged

**Comment by osdiab** [comment]
@gillchristian i don't see any merge conflicts with master?

**Comment by gillchristian** [comment]
There are conflicts now after merging #25 :grin:
